name: "WXT Submit"
author: "ryohidaka <39184410+ryohidaka@users.noreply.github.com>"
description: "A GitHub Action that submits new versions of an extension created with WXT for review."
branding:
  color: green
  icon: send
inputs:
  # Common Options
  dry-run:
    description: "Dry Run Flag"
    required: false
    default: false
  root-path:
    description: "The root path of the wxt project. Default is the current directory."
    required: false
    default: "."

  # Inputs for Chrome Extension
  chrome:
    required: false
    default: false
  chrome-extension-id:
    description: "Chrome Extension ID"
  chrome-client-id:
    description: "Chrome Client ID"
  chrome-client-secret:
    description: "Chrome Client Secret"
  chrome-refresh-token:
    description: "Chrome Refresh Token"

  # Inputs for Firefox Addon
  firefox:
    required: false
    default: false
  firefox-extension-id:
    description: "Firefox Extension ID"
  firefox-jwt-issuer:
    description: "Firefox JWT Issuer"
  firefox-jwt-secret:
    description: "Firefox JWT Secret"

  # Inputs for Edge Extension
  edge:
    required: false
    default: false
  edge-product-id:
    description: "Edge Product ID"
  edge-client-id:
    description: "Edge Client ID"
  edge-client-secret:
    description: "Edge Client Secret"
  edge-access-token-url:
    description: "Edge Access Token URL"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Check if Dryrun is enabled
      run: $GITHUB_ACTION_PATH/scripts/check_dry_run.sh "${{ inputs.dry-run }}"
      shell: bash

    - name: Check required inputs for Chrome Extension
      if: ${{ inputs.chrome == 'true' }}
      run: $GITHUB_ACTION_PATH/scripts/check_chrome_inputs.sh "${{ inputs.chrome-extension-id }}" "${{ inputs.chrome-client-id }}" "${{ inputs.chrome-client-secret }}" "${{ inputs.chrome-refresh-token }}"
      shell: bash

    - name: Check required inputs for Firefox Addon
      if: ${{ inputs.firefox == 'true' }}
      run: $GITHUB_ACTION_PATH/scripts/check_firefox_inputs.sh "${{ inputs.firefox-extension-id }}" "${{ inputs.firefox-jwt-issuer }}" "${{ inputs.firefox-jwt-secret }}"
      shell: bash

    - name: Check required inputs for Edge Extension
      if: ${{ inputs.edge == 'true' }}
      run: $GITHUB_ACTION_PATH/scripts/check_edge_inputs.sh "${{ inputs.edge-product-id }}" "${{ inputs.edge-client-id }}" "${{ inputs.edge-client-secret }}" "${{ inputs.edge-access-token-url }}"
      shell: bash

    - uses: pnpm/action-setup@v4
      with:
        version: "latest"

    - uses: actions/setup-node@v6
      with:
        node-version: latest
        cache: "pnpm"
        cache-dependency-path: ${{ inputs.root-path }}

    - name: Install dependencies
      run: $GITHUB_ACTION_PATH/scripts/install_dependencies.sh "${{ inputs.root-path }}"
      shell: bash

    - name: Submit to Chrome
      if: ${{ inputs.chrome == 'true' }}
      run: $GITHUB_ACTION_PATH/scripts/submit_to_chrome.sh "${{ inputs.root-path }}" "${{ inputs.dry-run }}"
      shell: bash
      env:
        CHROME_EXTENSION_ID: ${{ inputs.chrome-extension-id }}
        CHROME_CLIENT_ID: ${{ inputs.chrome-client-id }}
        CHROME_CLIENT_SECRET: ${{ inputs.chrome-client-secret }}
        CHROME_REFRESH_TOKEN: ${{ inputs.chrome-refresh-token }}

    - name: Submit to Firefox
      if: ${{ inputs.firefox == 'true' }}
      run: $GITHUB_ACTION_PATH/scripts/submit_to_firefox.sh "${{ inputs.root-path }}" "${{ inputs.dry-run }}"
      shell: bash
      env:
        FIREFOX_EXTENSION_ID: ${{ inputs.firefox-extension-id }}
        FIREFOX_JWT_ISSUER: ${{ inputs.firefox-jwt-issuer }}
        FIREFOX_JWT_SECRET: ${{ inputs.firefox-jwt-secret }}

    - name: Submit to Edge
      if: ${{ inputs.edge == 'true' }}
      run: $GITHUB_ACTION_PATH/scripts/submit_to_edge.sh "${{ inputs.root-path }}" "${{ inputs.dry-run }}"
      shell: bash
      env:
        EDGE_PRODUCT_ID: ${{ inputs.edge-product-id }}
        EDGE_CLIENT_ID: ${{ inputs.edge-client-id }}
        EDGE_CLIENT_SECRET: ${{ inputs.edge-client-secret }}
        EDGE_ACCESS_TOKEN_URL: ${{ inputs.edge-access-token-url }}
